apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-sidecar
spec:
  mode: sidecar
  hostNetwork: false
  image: otel/opentelemetry-collector-contrib-dev:latest
  initContainers:
    - image: hrexed/dt_enrichment:0.1
      imagePullPolicy: Always
      name: dt-enrich
      volumeMounts:
      - mountPath: /var/lib/dynatrace/enrichment
        name: data-ingest-enrichment
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      batch:
        send_batch_max_size: 1000
        timeout: 30s
        send_batch_size : 800

      memory_limiter:
        check_interval: 1s
        limit_percentage: 70
        spike_limit_percentage: 30

      attributes:
        actions:
           - key: dt.kubernetes.cluster.id
             action : insert
             value: ${dt.kubernetes.cluster.id}
           - key: "k8s.pod.uid"
             action : insert
             value: ${k8s.pod.uid}
           - key: k8s.pod.name
             action : insert
             value: ${k8s.pod.name}
           - key: k8s.namespace.name
             action : insert
             value: ${k8s.namespace.name}
    
      resource:
        attributes:
           - key: dt.kubernetes.cluster.id
             action : insert
             value: ${dt.kubernetes.cluster.id}
           - key: "k8s.pod.uid"
             action : insert
             value: ${k8s.pod.uid}
           - key: k8s.pod.name
             action : insert
             value: ${k8s.pod.name}
           - key: k8s.namespace.name
             action : insert
             value: ${k8s.namespace.name}
           
    
    exporters:
      logging:
        loglevel: debug

      otlp:
        endpoint: oteld-collector.default.svc.cluster.local:4317
        tls:
          insecure: true

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter,resource,attributes,batch]
          exporters: [otlp]
        metrics:
          receivers: [otlp]
          processors: [memory_limiter,resource,attributes,batch]
          exporters: [otlp]